name: Deploy to Azure VM

on:
  pull request:
    branches:
      - master      # change if needed (dev / prod)
  workflow_dispatch:

jobs:
  
  deploy:
  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
